version: "3.5"

services:
  local_db:
    container_name: local_db
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-149800}"
      PGDATA: /data/postgres
    volumes:
      - pgdata:/data/postgres
      - ./backups:/backups
    ports:
      - "${POSTGRES_PORT:-5801}:5432"
    restart: unless-stopped

  local_admin:
    container_name: local_db_admin
    image: dpage/pgadmin4:6.1
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-admin}"
    volumes:
      - ./tmp/storages/pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    depends_on:
      - local_db

volumes:
  pgdata: